helpcenter/urls.py
from django.conf.urls import url , include
from oprapp import views
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from  . import views

urlpatterns = [

    url(r'^$', views.HelpCenterIndex.as_view(), name='help_center'),
    url(r'^category/(?P<pk>\d+)$',views.HelpCenterDetail.as_view(), name = "help_center_detail"),
]

# development environment
if settings.DEBUG:
    # upload image
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oneplanet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from registration.backends.hmac.views import RegistrationView
# from registration.backends.model_activation.views import RegistrationView
from oprapp import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from oprapp.forms import SignUpForm
from oprapp.forms import UpdateProfileForm
from cuser.forms import AuthenticationForm
from django.conf import settings
from django.conf.urls.static import static
from helpcenter.views import terms_of_service, privacy_policy
from django.views.generic import ListView
from review.models import Review
from fastreview.views import (fast_review,
                              load_questions,
                              load_questions_by_category,
                              rated_questions_entities,
                              rated_questions_reviews)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # rest api
    url(r'^api/', include('restapi.urls')),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=SignUpForm), name='registration_register'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/login/$', auth_views.login, {'authentication_form': AuthenticationForm}, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    # user dashboard
    url(r'^dashboard/$', login_required(views.Dashboard.as_view()), name="dashboard"),
    # password reset
    url(r'^accounts/password_reset/$', auth_views.password_reset, name='password_reset'),
    # password reset done
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    # password reset form
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    # password reset done confirmation
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    # dashboard change password
    url(r'^dashboard/change-password/$', login_required(views.ChangePassword.as_view()), name='change_password'),
    # dashboard delete account
    url(r'^dashboard/delete-account/$', login_required(views.DeleteAccount.as_view()), name='delete_account'),
    # dashboard update profile information#
    url(r'^dashboard/(?P<pk>\d+)/update-profile/$', views.update_profile, name='update_profile'),
    # dashboard change password
    url(r'^dashboard/(?P<pk>\d+)/change-name/$', views.update_name, name='change_name'),
    # dashboard upload profile picture#
    url(r'^dashboard/upload-profile-pic/$', login_required(views.UploadProfilePicture.as_view()),
        name='upload_profile_picture'),
    # dashboard delete profile picture
    url(r'^dashboard/delete-profile-picture/$', views.delete_profile_picture, name='delete_profile_picture'),
    # dashboard change email#
    url(r'^dashboard/personal-email/$', views.change_email, name='change_email'),
    # give feedback #
    url(r'^give-feedback/$', views.feedback, name='give_feedback'),
    url(r'^feedback-confirm/$', views.feedback_confirm, name='feedback_confirm'),
    # help center
    url(r'^help/', include('helpcenter.urls')),
    # ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # legal
    url(r'^legal/terms', terms_of_service, name="terms_of_service"),
    url(r'^legal/privacy', privacy_policy, name="privacy_policy"),
    # index page
    url(r'^$', views.index, name="index"),
    # reviews part
    url(r'^review/', include('review.urls')),
    url(r'^element/(?P<place_id>[-\w]+)/(?P<search_type>[-\w]+)', views.ElementView.as_view(), name="element_view"),
    # element reviews
    url(r'^element/(?P<place_id>[-\w]+)/(?P<search_type>[-\w]+)/(?P<reviews>\d+)', views.ElementView.as_view(), name="element_view"),
    url(r'^element/(?P<place_id>[-\w]+)/(?P<reviews>\d+)', views.ElementView.as_view(), name="element_view"),
    url(r'^element/(?P<place_id>[-\w]+)/', views.ElementView.as_view(), name="element_view"),
    url(r'^review-listing/(.*)', views.reviewsOfElement, name='reviews_of_element'),
    url(r'^review-listing/', ListView.as_view(model=Review), name='review_list'),
    # review like and dislike
    url(r'^(?P<review_id>\d+)/vote/$', views.up_down_vote, name='like_dislike'),
    # add to favorites
    url(r'^add-to-favorites', views.add_to_favorites, name='add_to_favorites'),
    #remove from favorites
    url(r'^remove_from_favorites', views.remove_from_favorites, name='remove_from_favorites'),
    #invite a friend to OPR
    url(r'^invite', login_required(views.InviteFriend.as_view()), name='invite_friend'),
    # make a fast review from the sidebar
    url(r'^fast-review', fast_review, name='fast_review'),
    # load questions dynamically from sidebar
    url(r'^load-question', load_questions, name='load_question'),
    # load rated questions for every category for an Entity/Element
    url(r'^load-rated-question', rated_questions_entities, name='load_rated_question'),
    # load rated questions for every review
    url(r'^rated-questions-reviews', rated_questions_reviews, name='rated_questions_reviews'),
    # load questions based on category
    url(r'^category-load-questions', load_questions_by_category, name='load_question_category'),
]

# development environment
if settings.DEBUG:
    # upload image
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oprapp/urls.py
from django.conf.urls import url ,include
from oprapp import views


urlpatterns = [

]

helpcenter/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from ckeditor.fields import RichTextField

# Create your models here.

class HelpCategory(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("help_center_detail", kwargs={"pk": self.pk})


class HelpArticle(models.Model):
    # one category has many articles
    category = models.ForeignKey(HelpCategory, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = RichTextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("help_center_detail", kwargs={"pk": self.category.pk})


class Legal(models.Model):

    title = models.CharField(max_length=255)
    content = RichTextField()
    
    def __str__(self):
        return self.title

helpcenter/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views import generic
from .models import HelpCategory
from django.shortcuts import render
from .models import Legal
# Create your views here.

class HelpCenterIndex(generic.ListView):
    template_name = "helpcenter/help_center.html"
    # pass data as albums_list
    context_object_name = "help_categories"
    def get_queryset(self):
        return list(reversed(HelpCategory.objects.all()))

# DetailView Class
class HelpCenterDetail(generic.DetailView):
    model = HelpCategory
    template_name = "helpcenter/help_center_detail.html"

def terms_of_service(request):
    objects = Legal.objects.all()
    return render(request, "helpcenter/legal.html",{"legal":objects[0]})

def privacy_policy(request):
    objects = Legal.objects.all()
    return render(request, "helpcenter/legal.html",{"legal":objects[1]})

templates/helpcenter/help_center.html
{% extends 'base.html' %}
{% block content %}
<div class="help-center-box">
<div class="jumbotron help-center-header">
    <h3>Frequently Asked Questions</h3>
</div>

<div class="container">
<div class="row" style="margin: auto; margin-top: 1.5%;">

        {% for h_category in help_categories %}
    <a class="help-category-link" href="{% url 'help_center_detail' h_category.id %}">
        <div class=" help-category-item card  col-md-3 col-xs-12 col-sm-6">
            <div class="card-block">
                    <span class="help-item-title">{{h_category.title}}</span>
            </div>
        </div>
    </a>
    {%endfor%}
</div>
</div>
</div>
{% endblock %}

templates/helpcenter/help_center_detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="wrapper">
<div class="help-center-box">
<div class="container article-box">


    <ol class="breadcrumb col-md-12 ">
        <li><a href="{% url 'help_center' %}">FAQ</a></li>
        <li class="active">{{helpcategory.title}}</li>
    </ol>

    <div class="page-header col-md-12 col-xs-12">
        <h2>{{helpcategory.title}}</h2>
    </div>

    <div class="row">

            <div class="col-md-8 col-sm-8 col-xs-12 pull-left">
            {% for article in helpcategory.helparticle_set.all%}
                <button class="accordion help-accordion"><div>{{article.title}}</div><i class="glyphicon glyphicon-chevron-down pull-right"></i></button>
            <div class="panel-accordion">
                    <p class="content">
                        {% render_field article.content %}
                    </p>
            </div>
            {%endfor %}
            </div>


    </div>
</div>
</div>
</div>
{% endblock %}

templates/helpcenter/legal.html
{% extends 'base.html' %}
{% block content %}
<div class="help-center-box">
    <div class="jumbotron help-center-header">
        <h3>{{legal.title}}</h3>
    </div>

    <div class="container">
        <div class="row" style="margin: auto; margin-top: 1.5%;">
          {{legal.content|safe}}
        </div>
    </div>
</div>
{% endblock %}