oneplanet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from registration.backends.hmac.views import RegistrationView
# from registration.backends.model_activation.views import RegistrationView
from oprapp import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from oprapp.forms import SignUpForm
from oprapp.forms import UpdateProfileForm
from cuser.forms import AuthenticationForm
from django.conf import settings
from django.conf.urls.static import static
from helpcenter.views import terms_of_service, privacy_policy
from django.views.generic import ListView
from review.models import Review
from fastreview.views import (fast_review,
                              load_questions,
                              load_questions_by_category,
                              rated_questions_entities,
                              rated_questions_reviews)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # rest api
    url(r'^api/', include('restapi.urls')),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=SignUpForm), name='registration_register'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/login/$', auth_views.login, {'authentication_form': AuthenticationForm}, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    # user dashboard
    url(r'^dashboard/$', login_required(views.Dashboard.as_view()), name="dashboard"),
    # password reset
    url(r'^accounts/password_reset/$', auth_views.password_reset, name='password_reset'),
    # password reset done
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    # password reset form
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    # password reset done confirmation
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    # dashboard change password
    url(r'^dashboard/change-password/$', login_required(views.ChangePassword.as_view()), name='change_password'),
    # dashboard delete account
    url(r'^dashboard/delete-account/$', login_required(views.DeleteAccount.as_view()), name='delete_account'),
    # dashboard update profile information#
    url(r'^dashboard/(?P<pk>\d+)/update-profile/$', views.update_profile, name='update_profile'),
    # dashboard change password
    url(r'^dashboard/(?P<pk>\d+)/change-name/$', views.update_name, name='change_name'),
    # dashboard upload profile picture#
    url(r'^dashboard/upload-profile-pic/$', login_required(views.UploadProfilePicture.as_view()),
        name='upload_profile_picture'),
    # dashboard delete profile picture
    url(r'^dashboard/delete-profile-picture/$', views.delete_profile_picture, name='delete_profile_picture'),
    # dashboard change email#
    url(r'^dashboard/personal-email/$', views.change_email, name='change_email'),
    # give feedback #
    url(r'^give-feedback/$', views.feedback, name='give_feedback'),
    url(r'^feedback-confirm/$', views.feedback_confirm, name='feedback_confirm'),
    # help center
    url(r'^help/', include('helpcenter.urls')),
    # ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # legal
    url(r'^legal/terms', terms_of_service, name="terms_of_service"),
    url(r'^legal/privacy', privacy_policy, name="privacy_policy"),
    # index page
    url(r'^$', views.index, name="index"),
    # reviews part
    url(r'^review/', include('review.urls')),
    url(r'^element/(?P<place_id>[-\w]+)/(?P<search_type>[-\w]+)', views.ElementView.as_view(), name="element_view"),
    # element reviews
    url(r'^element/(?P<place_id>[-\w]+)/(?P<search_type>[-\w]+)/(?P<reviews>\d+)', views.ElementView.as_view(), name="element_view"),
    url(r'^element/(?P<place_id>[-\w]+)/(?P<reviews>\d+)', views.ElementView.as_view(), name="element_view"),
    url(r'^element/(?P<place_id>[-\w]+)/', views.ElementView.as_view(), name="element_view"),
    url(r'^review-listing/(.*)', views.reviewsOfElement, name='reviews_of_element'),
    url(r'^review-listing/', ListView.as_view(model=Review), name='review_list'),
    # review like and dislike
    url(r'^(?P<review_id>\d+)/vote/$', views.up_down_vote, name='like_dislike'),
    # add to favorites
    url(r'^add-to-favorites', views.add_to_favorites, name='add_to_favorites'),
    #remove from favorites
    url(r'^remove_from_favorites', views.remove_from_favorites, name='remove_from_favorites'),
    #invite a friend to OPR
    url(r'^invite', login_required(views.InviteFriend.as_view()), name='invite_friend'),
    # make a fast review from the sidebar
    url(r'^fast-review', fast_review, name='fast_review'),
    # load questions dynamically from sidebar
    url(r'^load-question', load_questions, name='load_question'),
    # load rated questions for every category for an Entity/Element
    url(r'^load-rated-question', rated_questions_entities, name='load_rated_question'),
    # load rated questions for every review
    url(r'^rated-questions-reviews', rated_questions_reviews, name='rated_questions_reviews'),
    # load questions based on category
    url(r'^category-load-questions', load_questions_by_category, name='load_question_category'),
]

# development environment
if settings.DEBUG:
    # upload image
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oprapp/urls.py
from django.conf.urls import url ,include
from oprapp import views


urlpatterns = [

]

oprapp/forms.py
from django import forms
from django.core.validators import RegexValidator
from registration.forms import RegistrationForm
from django.conf import settings
from cuser .models import CUser
from .models import Profile, PromotionCodes
from django.contrib.auth import get_user_model
from review.models import Review, Rating, RatingCategory
from django_libs.loaders import load_member
from django.utils.translation import get_language
User = get_user_model()


# Places form
class PlaceSearchForm(forms.Form):
    Place = forms.CharField(label='Place', max_length=100)


class ReviewForm(forms.ModelForm):

    def __init__(self, reviewed_item, user=None, *args, **kwargs):
        self.user = user
        self.reviewed_item = reviewed_item
        self.widget = load_member(getattr(settings, 'REVIEW_FORM_CHOICE_WIDGET', 'django.forms.widgets.Select'))()
        super(ReviewForm, self).__init__(*args, **kwargs)
        # Dynamically add fields for each rating category
        for category in RatingCategory.objects.all():
            field_name = 'category_{0}'.format(category.pk)
            choices = category.get_choices()
            # self.fields[field_name] = forms.ChoiceField(choices=choices, label=category.name, help_text=category.question, widget=self.widget, )
            self.fields[field_name] = forms.ChoiceField(choices=choices, label=category.name, help_text=category.question, widget=forms.widgets.CheckboxSelectMultiple(attrs={'class':'rating-input'}), )
            # self.fields[field_name].required = category.required
            self.fields[field_name].required = False
            if self.instance.pk:
                try:
                    self.initial.update({'category_{0}'.format(category.pk): Rating.objects.get(review=self.instance, category=category).value, })
                except Rating.DoesNotExist:
                    pass

    def save(self, *args, **kwargs):
        if not self.instance.pk:
            self.instance.user = self.user
            self.instance.reviewed_item = self.reviewed_item
            self.instance.language = get_language()
        self.instance = super(ReviewForm, self).save(*args, **kwargs)
        # Update or create ratings
        for field in self.fields:
            if field.startswith('category_'):
                rating, created = Rating.objects.get_or_create(review=self.instance, category=RatingCategory.objects.get(pk=field.replace('category_', '')), )
                rating.value = self.cleaned_data[field]
                rating.save()

        self.instance.average_rating = self.instance.get_average_rating()
        self.instance.save()

        return self.instance
    class Meta:
        model = Review
        fields = ('content',)



class CustomReviewForm(ReviewForm):
    """Form to make use of the review extra info."""

    def __init__(self, reviewed_item, user=None, *args, **kwargs):
        super(CustomReviewForm, self).__init__(reviewed_item, user, *args, **kwargs)
        # choices = [(x.pk, x.name) for x in WeatherCondition.objects.all()]
        # self.fields['weather_conditions'] = forms.fields.ChoiceField(choices=choices)

    def save(self, *args, **kwargs):
        self.instance = super(CustomReviewForm, self).save(*args, **kwargs)
        # ReviewExtraInfo.objects.create(type='weather_conditions', review=self.instance, content_object=WeatherCondition.objects.get(pk=self.cleaned_data['weather_conditions']), )
        return self.instance


# force unique emails
def force_unique_email(value):

    email = value
    email_qs = User.objects.filter(email=email)
    if email_qs.exists():
        raise forms.ValidationError("This email is already registered, Please try a different email address")

def check_promo_code(value):
    promo_code = value
    try:
        codes=PromotionCodes.objects.get(promo_code=promo_code)
    except PromotionCodes.DoesNotExist:
        codes=None

    if codes is None:
        raise forms.ValidationError("This promotion code is already registered or does not exist, Please try a different promotion code")
    else:
        codes.save()

# User signup form
class SignUpForm(RegistrationForm):
    # makes the field a password field.

    GENDER_CHOICES = (
        ('','Select your gender'),
        ('Male', 'Male'),
        ('Female', 'Female'),
	('Other', 'Other'),
 
    )

    city = forms.CharField(label= "City")
    date_of_birth = forms.DateField(widget=forms.DateInput(format='%Y-%m-%d'),
    input_formats=('%Y-%m-%d',))

    gender = forms.ChoiceField(choices=GENDER_CHOICES,
                               widget=forms.Select(attrs={
                                   "id": "gender",
                                   "tabindex": "1",
                               }), required=True)

    # using the username as email
    email = forms.EmailField(label="Email Address", validators=[force_unique_email])
    password1= forms.CharField(widget=forms.PasswordInput, min_length=8, label ="Password")
    password2 = forms.CharField(widget=forms.PasswordInput, min_length=8, label="Retype Password")
    first_name = forms.CharField(label=" First and last name")
    promo_code = forms.CharField(label="Promotion code", validators=[check_promo_code])

    class Meta:
        model = CUser
        fields = ["first_name","email","password1","password2"]


#  change name (dashboard)
class ChangeNameForm (forms.ModelForm):
    first_name = forms.CharField(min_length=2, required=True)
    last_name = forms.CharField(required=False)

    class Meta:
        model = CUser
        fields = ["first_name", "last_name"]


# update user profile (dashboard)
class UpdateProfileForm (forms.ModelForm):
    GENDER_CHOICES = (
        ('', 'Select your gender'),
        ('Male', 'Male'),
        ('Female', 'Female'),
	    ('Other', 'Other'),
    )

    city = forms.CharField(label="city", required=True)
    birth_date = forms.DateField(widget=forms.DateInput(format='%Y-%m-%d', attrs={
       "id":"id_date_of_birth",
    }),input_formats=('%Y-%m-%d',), required=True, label="Date of birth")

    gender = forms.ChoiceField(choices=GENDER_CHOICES,
                               widget=forms.Select(attrs={
                                   "id": "gender",
                                   "tabindex": "1",
                               }), required=True)

    about_me = forms.CharField(widget=forms.Textarea(attrs={
        "rows":"5",
    }), required=False, label="Write something about yourself")

    class Meta:
        model = Profile
        fields = ["about_me","address","city","phone_number","birth_date","gender"]


# change user email (dashboard)
class ChangeUserEmailForm(forms.ModelForm):
    email = forms.EmailField(required=True,   label= "new email")
    password = forms.CharField(widget=forms.PasswordInput, min_length=8, label="Enter your password")

    class Meta:
        model = User
        fields = ["email","password"]

    def clean(self):
        email = self.cleaned_data.get("email")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email is already registered, Please try a different email address")
        return email


# upload profile picture (dashboard)
class ProfilePictureForm(forms.ModelForm):
        profile_picture = forms.ImageField(required= True)

        class Meta:
            model = Profile
            fields = ["profile_picture",]


class FeedbackForm(forms.Form):
    features_list = (
        ('', 'Please select a subject'),
        ('login', 'login'),
        ('signup', 'signup'),
        ('search', 'search'),
        ('ratings', 'rating'),
        ('reviews', 'reviews'),
        ('dashboard', 'dashboard'),
        ('comments', 'comments'),
        ('design', 'design'),
        ('other', 'other'),
    )
    feedback_subject = forms.ChoiceField(choices=features_list,
                               widget=forms.Select(attrs={
                               }), required=True)
    message = forms.CharField(widget=forms.Textarea(attrs={
        "rows": "5",
        "placeholder": "Please include a detailed description of your idea or suggestion"
    }), required=True, label="Your Feedback", min_length=3)


class InviteForm(forms.Form):
    email = forms.EmailField(label="Email Address", required=True)

    def clean(self):
        cleaned_data = super(InviteForm, self).clean()
        email = cleaned_data.get("email")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError(
                "The contact you entered is already a member,"
                " please try another email address."
            )

templates/oprapp/feedback.html
{% extends "base.html" %}
{% load staticfiles %}
{%block content %}
<div class="wrapper">
<div class="container">
    <div class="row">
        <div class="col-md-8 col-xs-12 feedback-box">
            <form method="post" action="{% url 'give_feedback' %}" class="js-change-password-form">
                {% csrf_token %}

                <div class="page-header">
                    <h3>Give Us Feedback about an One Planet Rating Feature</h3>
                </div>
                <p>Let us know how we can improve One Planet Rating</p>
                {% load widget_tweaks %}
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                    <label>{{field.label}}</label>
                    {% render_field field class="form-control"%}
                    {% for error in field.errors %}
                    <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="pull-right"><button type="submit" class="btn btn-primary">Send feedback</button></div>
            </form>
        </div>
    </div>
</div>
</div>


{% endblock %}

templates/oprapp/feedback_confirmation.html
{% extends 'base.html' %}

{%block content %}
<div class="wrapper register-login-wrapper">
    <div class="container">
        <div class="row">
            <p>Thanks for taking the time to give us feedback. Your feedback is valuable to us </p>
    </div>
    </div>
</div>

{% endblock %}

templates/oprapp/index.html
{# Load the tag library #}
{% extends "base.html" %}
{% block main %}

    {% load bootstrap3 %}
    {% load tags %}

<div class="main-container">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-lg-12">
                <div class="main-content">
                    <form id="index-form" class="form search_form" action="/" method="post">
                        {%csrf_token%}
                        <div class="cc-selector" id="index_css_selector">
                            {% for search_cat in search_categories %} {% get_icon_value search_cat.icon as search_cat_icon %} {% if search_cat_icon%}
                            <input id="{{search_cat.name}}" type="radio" name="type" value="{{search_cat.name}}">
                            <label class="type" for="{{search_cat.name}}" style="background-image: url(staticfiles/svg/{{search_cat_icon}});"></label>
                            {% endif %} {% endfor %}
                            <input id="helper_search_type" type="radio" name="type" value="" style="display:none">
                        </div>
                        <div class="row search-area">
                            <div class="col-xs-12 col-lg-offset-2 col-lg-8" id="search_input">
                                <div class="input-group">
                                    <input type="text" class="form-control" aria-label="..." name="Place" id="id_Place" placeholder="">
                                    <div class="input-group-btn">
                                        <button type="submit" id="search_btn" class="btn btn-secondary">Search {{search_categories.0.name}}</button>
                                        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu search-categories-list">
                                            {% for search_cat in search_categories %}
                                            <li><a>{{search_cat.name}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-lg-12">
                                <div class="hashtag-text">
                                    <h1>Ratings. Reviews. Rewards.</h1>
                                    <h3>#SustainableTourism</h3>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}
{%block js%}


<script>

    (function (){

       var active_cat = document.querySelector(".cc-selector input");
       active_cat.setAttribute("checked", "checked")
       $("#id_Place").attr("placeholder", "City or place name")



// basic ajax call to test API methods

      $.ajax({
    url: 'https://www.oneplanetrating.org/api/rest-auth/get-user/',
    headers: {
        'Authorization':'Token d18bc9b98f7736ef919cebeceb228d71796157fe',
        'Content-Type':'application/json'
    },
    method: 'GET',
    dataType: 'json',
    success: function(response){
      console.log(response);
    }
  });

  // end

      })();



</script>
{%endblock js%}

templates/oprapp/invitation_email.html
<!DOCTYPE html>
<html>

<head>
    {% load staticfiles %}
    {% load i18n %}
    {% load tags %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
    <link rel="icon" href="../favicon.ico" type="image/x-icon">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="http://{{get_site_url}}{% static 'css/email_welcome.css' %}" rel="stylesheet">
</head>
<body>

<div class="container">
    <div class="text-center">
        <div class="col-md-12 welcome-title"  style="text-align: center;  padding-top: 30px;
    padding-bottom: 20px;">
            <h1 style="  font-family: 'Roboto', sans-serif;" class="text-center">Be one of the first to join One Planet Rating</h1>
        </div>

        <div class="col-md-6 col-md-offset-3" style="width: 50%;margin-left: 30%;">
            <img src="cid:logo-side-text.png" alt="opr-logo" class="brand-logo" style="width: 75%;">
        </div>

    </div>
    <div class="col-md-6 col-md-offset-1 aurora-img text-center" style="width: 100%">
        <img src="cid:aurora_with_activities.png" alt="aurora image" class="img-responsive"  style="width: 100%">
    </div>

    <div class="col-md-6 col-md-offset-1 content text-center" style="padding: 0px 10px 20px 12px;">
        <p style=" font-size: 15px; font-weight: 900;font-family: 'Roboto', sans-serif;text-align: left;padding-top: 10px;">
            Your early access invite to One Planet Rating (beta) is here!</p>
        <p style=" font-size: 15px; font-weight: 900;font-family: 'Roboto', sans-serif;text-align: left;padding-top: 10px;">
            With this special early access, you are among a select group that will help accelerate our movement towards sustainable tourism. </p>
        <p style=" font-size: 15px; font-weight: 900;font-family: 'Roboto', sans-serif;text-align: left;padding-top: 10px;">
            Our first 500 users will automatically be elevated to the second membership level later this year as we begin our membership program. This means you’ll also be the first to receive special discounts and offers on travel and sustainability products.
        </p>

        <p style=" font-size: 15px; font-weight: 900;font-family: 'Roboto', sans-serif;text-align: left;padding-top: 10px;">
            We’re still rolling out new features and improving the service, so don't hesitate to give us a shout with suggestions of your own.
        </p>

        <p style=" font-size: 15px; font-weight: 900;font-family: 'Roboto', sans-serif;text-align: left;padding-top: 10px;">
            Happy rating! Let’s make travel more sustainable, one review at a time.
        </p>
        <div class="" style="margin: 40px 0px 20px 0px; text-align:center;">
            <a  href="http://{% get_site_url %}/accounts/register/" target="_blank" style="padding: 20px;
          border: solid 1px transparent;
          background-color: #3198cc;
          color: white;
          text-decoration: none;
          border-radius: 3px;">ACCEPT INVITATION
            </a>
        </div>
    </div>

    <hr class="col-md-10 col-md-offset-1" style="
    display: block;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-color: #356a70;
    border-width: 2px;">
    <div class="col-xs-12 text-center links" style="font-size: 18px; padding: 0px 10px 0px 15px; text-align:center;">
        Go to
        <a href="http://{% get_site_url %}" target="_blank" style="color: black; text-decoration: none;">OPR</a> |
	<a href="http://{% get_site_url %}/help/category/3" target="_blank" style="color: black; text-decoration: none;">FAQ</a> |
        <a href="http://{% get_site_url %}/legal/privacy" target="_blank" style="color: black; text-decoration: none;">Privacy Policy</a> |
        <a href="http://www.oneplanetrating.com/" target="_blank" style="color: black; text-decoration: none;">Corporate site</a>
    </div>
    <div class="col-xs-12 col-md-8 col-md-offset-2 text-center icons" style="padding-top: 15px; text-align: center; padding-bottom: 70px;">
        <a href="https://www.facebook.com/oneplanetrating/" target="_blank"><img style="height: 50px;padding: 20px;" src="cid:facebook-email.png" alt="facebook"></a>
        <a href="https://twitter.com/OnePlanetRating" target="_blank"><img style="height: 50px;padding: 20px;" src="cid:twitter-email.png" alt="twitter" ></a>
        <a href="https://www.instagram.com/oneplanetrating/" target="_blank"><img style="height: 50px;padding: 20px;" src="cid:instagram-email.png" alt="instagram"></a>
    </div>
</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</html>

templates/oprapp/invitation_success.html
{% extends 'base.html' %}

{%block content %}
<div class="wrapper register-login-wrapper">
    <div class="container">
        <div class="row">
            <p>Thanks for taking the time to help OPR grow. Your friend will receive an invitation email from OPR team, with a link to create an account</p>
        </div>
    </div>
</div>
{% endblock %}

templates/oprapp/invite.html
{% extends "base.html" %}
{% load staticfiles %}
{%block content %}
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-xs-12 feedback-box">
                <form method="post" action="{% url 'invite_friend' %}">
                    {% csrf_token %}

                    {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}

                    <div class="page-header">
                        <h3>Invite a friend to One Planet Rating</h3>
                    </div>
                    <p>Enter your friend's email address to send him an invitation to join OPR</p>
                    {% load widget_tweaks %}
                    {% for field in form %}
                    <div class="form-group{% if field.errors %} has-error{% endif %}">
                        <label>{{field.label}}</label>
                        {% render_field field class="form-control"%}
                        {% for error in field.errors %}
                        <p class="help-block">{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% endfor %}
                    <div class="pull-right"><button type="submit" class="btn btn-primary">Send invitation</button></div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/oprapp/page_not_exist.html
{% extends "base.html" %}
{% block main %}
{% load staticfiles %}
<div class="container">

    <div class="col-md-12 col-sm-12 col-xs-12" style="padding:100px; margin-bottom:100%">
        <p>This page does not exist</p>
    </div>
</div>
{% endblock %}
{%block js%}
{%endblock js%}

templates/oprapp/search_bar.html
<div class="search-bar" style="{%if request.user.is_authenticated%} margin-top: 76px; {%else%} margin-top: 66px;{%endif%}">
    <div class="container">
        <form action="/" class="form search_form" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-xs-12">
                    <div class="input-group">
                        <select class="form-control " name="type" id="selector">
                            {% for search_cat in search_categories %}
                            <option>{{search_cat.name}}</option>
                            {%endfor%}
                        </select>
                        <input type="text" id="id_Place" class="search-bar-text form-control" name="Place" placeholder="City or place name">
                        <span class="input-group-btn">
                         <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>